version: '2'

services:
  web:
    build: .
    ports:
      - "9000:8000"
    depends_on:
      - dynamodb
      - redis
    environment:
      - DIAMONDB_REDIS_ADDRS=redis:6379
      - DIAMONDB_DYNAMODB_ENDPOINT=http://dynamodb:8000
  redis:
    image: redis:3.2.7
  dynamodb:
    image: deangiberson/aws-dynamodb-local:latest
    volumes:
      - ./tmp/dynamodb:/var/dynamodb_local
